### ISSUE TITLE
Yaml reader error when bundling the project into a local update site.

### ISSUE THREAD

**Issue by jiqicn** [EyeofBeholder-NLeSC/python-knime-extension#3]
By following the instruction, we need to firstly export the conda environment as a yml file including all the direct dependencies. However, by running the following code in terminal for creating the yml file, the result file will not be read properly by the build_python_extension tool:

```shell
conda env export --from-history > environment.yml
```

Error message:

```shell
Using bundle name 'org.nlesc.eye_of_beholder.channel.bin'.
Using plugin template from 'C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\bin\templates\conda-channel-plugin'.
Rendering plugin to 'C:\Users\qiji1\AppData\Local\Temp\tmphven5mki\org.nlesc.eye_of_beholder.channel.bin'...
Traceback (most recent call last):
  File "C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\bin\build_python_extension.py", line 352, in <module>
    build_extension(
  File "C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\bin\build_python_extension.py", line 54, in build_extension      
    _build_extension(extension_dir_path, output_repository_path, config, tempdir)
  File "C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\bin\build_python_extension.py", line 68, in _build_extension     
    bundles += _create_conda_channels(render_dir_path, force, config)
  File "C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\bin\build_python_extension.py", line 263, in _create_conda_channels
    return bundler.bundle()
  File "C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\bin\bundle_channels.py", line 83, in bundle
    bundles.append(self._bundle_fragment(platform=platform))
  File "C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\bin\bundle_channels.py", line 92, in _bundle_fragment
    env_spec = _load_env_spec(env_yml)
  File "C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\bin\bundle_channels.py", line 179, in _load_env_spec
    return yaml.safe_load(f)
  File "C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\lib\site-packages\yaml\__init__.py", line 125, in safe_load      
    return load(stream, SafeLoader)
  File "C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "C:\Users\qiji1\anaconda3\envs\knime-ext-bundling\lib\site-packages\yaml\reader.py", line 143, in check_printable  
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Workspace\knime_extension_python\basic\environment.yml", position 3
```

**Comment by jiqicn** [comment]
This seems to be the problem of the way of encoding when writing the result into file. Instead of using the command as described, the following cmd works properly:

```shell
conda env export --from-history -f environment.yml
```
or
```shell
conda env export | Out-File environment.yml -Encoding utf8NoBom
```

See this [link](https://github.com/conda/conda/issues/9749#issuecomment-721073051) for more explanation.
